# Generated by Django 4.0.1 on 2022-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
